package actions

import (
	"fmt"
	"time"

	"github.com/davidalvarez305/home_services/server/database"
	"github.com/davidalvarez305/home_services/server/models"
	"github.com/davidalvarez305/home_services/server/sessions"
	"github.com/davidalvarez305/home_services/server/types"
	"github.com/davidalvarez305/home_services/server/utils"
	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

type Lead struct {
	*models.Lead
}

type LeadLogin struct {
	UUID string `json:"uuid"`
}

type LeadQuote struct {
	StreetAddressLine1 string `json:"street_address_line_1"`
	StreetAddressLine2 string `json:"street_address_line_2"`
	StreetAddressLine3 string `json:"street_address_line_3"`
	City               string `json:"city"`
	CityID             int    `json:"city_id"`
	StateID            int    `json:"state_id"`
	State              string `json:"state"`
	ZipCode            string `json:"zip_code"`
	CreatedAt          int64  `json:"created_at"`
	Services           string `json:"services"`           // string separated by commas
	Photos             string `json:"photos"`             // string separated by commas
	PhotoDescriptions  string `json:"photo_descriptions"` // string separated by commas
}

type LeadQuotes []*LeadQuote

func (l *Lead) Save() error {
	return database.DB.Save(&l).First(&l).Error
}

func (l *Lead) Delete(leadId string) error {
	return database.DB.Where("id = ?", leadId).Delete(&l).Error
}

func (l *Lead) GetLead(leadId string) error {
	return database.DB.Where("id = ?", leadId).First(&l).Error
}

func (l *Lead) GetLeadByUUID(uuid string) error {
	return database.DB.Where("uuid = ?", uuid).First(&l).Error
}

func (l *Lead) GetLeadByEmail(email string) error {
	return database.DB.Where("email = ?", email).First(&l).Error
}

// Grabs userId from session, and then performs select query from the database.
func (lead *Lead) GetLeadFromSession(c *fiber.Ctx) error {
	sess, err := sessions.Sessions.Get(c)

	if err != nil {
		return err
	}

	leadUUID := sess.Get("lead_uuid")

	if leadUUID == nil {
		return err
	}

	err = lead.GetLeadByUUID(fmt.Sprintf("%v", leadUUID))

	return err
}

func (l *Lead) CreateLead(input *types.CreateLeadInput) error {

	l.Lead = &models.Lead{
		FirstName:   input.FirstName,
		LastName:    input.LastName,
		UUID:        uuid.New().String(),
		Email:       input.Email,
		PhoneNumber: input.PhoneNumber,
		CreatedAt:   time.Now().Unix(),
	}

	l.Lead.LeadMarketing = &models.LeadMarketing{
		Campaign:     input.Campaign,
		Source:       input.Source,
		Medium:       input.Medium,
		CampaignName: input.CampaignName,
		LeadChannel:  input.LeadChannel,
		ReferralURL:  input.ReferralURL,
		Keywords:     input.Keywords,
		LeadID:       l.Lead.ID,
	}

	// Assign lead
	companyId, err := FindCompanyIDByZipCodeAndService(input.ZipCode, input.Service)

	if err != nil {
		fmt.Printf("%+v\n", "Company not found.")
	}

	l.Lead.CompanyID = companyId

	return database.DB.Save(&l).First(&l).Error
}

func (l *Lead) Login(input *LeadLogin, c *fiber.Ctx) error {

	// Find Lead by UUID
	err := l.GetLeadByUUID(input.UUID)

	if err != nil {
		return err
	}

	err = l.GenerateLeadToken()

	if err != nil {
		return err
	}

	return err
}

// Destroy session.
func (l *Lead) LeadLogout(c *fiber.Ctx) error {
	sess, err := sessions.Sessions.Get(c)

	if err != nil {
		return err
	}

	err = sess.Destroy()

	return err
}

// Get all of the quotes generated by a user.
func (lq *LeadQuotes) GetQuotesByLead(leadId string) error {
	sql := `
	SELECT a.street_address_line1 AS street_address_line_1, a.street_address_line2 AS street_address_line_2, a.street_address_line3 AS street_address_line_3,
	c.city, c.id AS city_id, s.state, s.id AS state_id, q.zip_code,
	string_agg(ser.service, ',') AS services,
	string_agg(qp.image_url, ',') AS photos,
	string_agg(qp.description, ',') AS photo_descriptions
	FROM quote AS q
	LEFT JOIN quote_services AS qs
	on qs.quote_id  = q.id
	LEFT JOIN service AS ser
	on ser.id = qs.service_id
	LEFT JOIN quote_photos AS qp 
	on qp.quote_id = q.id
	LEFT JOIN address AS a
	ON a.id = q.address_id
	LEFT JOIN zip_code AS z
	ON z.zip_code = q.zip_code
	LEFT JOIN city AS c
	ON c.id = z.city_id
	LEFT JOIN state AS s
	ON s.id = z.state_id
	WHERE q.lead_id = ?
	GROUP BY a.street_address_line1, a.street_address_line2, a.street_address_line3,
	c.city, c.id, s.id, s.state, q.zip_code;
	`

	return database.DB.Raw(sql, leadId).Scan(&lq).Error
}

func (l *Lead) RecoverUUIDCode(uuid string) error {

	err := database.DB.Where("uuid = ?", uuid).First(&l).Error

	if err != nil {
		return err
	}

	title := "Your UUID Recovery Request"
	message := fmt.Sprintf("Your UUID Is: %s", l.UUID)
	err = utils.SendGmail(message, l.Email, title)

	if err != nil {
		return err
	}

	return nil
}

// Generate lead token that's used for confirming users' login request.
func (lead *Lead) GenerateLeadToken() error {
	lc := &LeadCode{}
	err := lc.GenerateLoginCode(lead.ID)

	if err != nil {
		return err
	}

	title := "Login Account Code"
	message := fmt.Sprintf("Enter this code: %s", lc.Code)
	err = utils.SendGmail(message, lead.Email, title)

	if err != nil {
		return err
	}

	return nil
}
